jQuery(document).ready(function($){$('.dropdown').on('click',function(e){e.preventDefault()
$('.dropdown').each(function(){$(this).removeClass('active')})
$(this).toggleClass('active')
$('.dropdown').each(function(){if(!$(this).hasClass('active')){$(this).find('.opts').hide()}})
$(this).find('.current_opt i').toggleClass(function(){if($(this).parents('dropdown').hasClass('active')){return 'i-ar-d'}else{return 'i-ar-u'}})
$(this).find('.opts').toggle()})
$('.opts a').each(function(){if($(this).hasClass('active')){var text=$(this).text()
$(this).parents('.dropdown').find('.current_opt span').text(text)}})
$('.opts a').on('click',function(e){e.preventDefault()
$(this).removeClass('active')
var text=$(this).text()
$(this).parents('.dropdown').find('.current_opt').addClass('sel')
$(this).parents('.dropdown').find('.current_opt span').text(text)
window.location.replace($(this).attr('href'))})
$('._menu_side').on('click',function(e){e.preventDefault()
$(this).parents('#right').toggleClass('show_full')})
var player=new Plyr('#yt_trailer_player')
$(function(){$('.lazy').lazy({delay:1000,})})
var defaultPage=2
$('#load-more').on('click',function(e){e.preventDefault()
$.ajax({type:'GET',url:'/ajax/movies/more',data:{page:defaultPage,filter:getUrlParameter('filter'),},dataType:'json',headers:{'X-CSRF-TOKEN':$('meta[name="_token"]').attr('content'),},success:function(data){defaultPage=data.page+1
$('.loaded-data').append(data.html)
if(data.hasMorePages==false){$('#load-more').remove()}},error:function(xhr,type){console.log('Ajax error!')},})})
$('#load-more-series').on('click',function(e){e.preventDefault()
$.ajax({type:'GET',url:'/ajax/series/more',data:{page:defaultPage,},dataType:'json',headers:{'X-CSRF-TOKEN':$('meta[name="_token"]').attr('content'),},success:function(data){defaultPage=data.page+1
$('.loaded-data').append(data.html)
if(data.hasMorePages==false){$('#load-more-series').remove()}},error:function(xhr,type){console.log('Ajax error!')},})})
$('#load-more-ramadan').on('click',function(e){e.preventDefault()
$.ajax({type:'GET',url:'/ajax/ramadan/more',data:{page:defaultPage,},dataType:'json',headers:{'X-CSRF-TOKEN':$('meta[name="_token"]').attr('content'),},success:function(data){defaultPage=data.page+1
$('.loaded-data').append(data.html)
if(data.hasMorePages==false){$('#load-more-series').remove()}},error:function(xhr,type){console.log('Ajax error!')},})})
$('#load-more-period').on('click',function(e){e.preventDefault()
var period=$(this).data('period');$.ajax({type:'GET',url:'/ajax/trending/more',data:{page:defaultPage,period:period,},dataType:'json',headers:{'X-CSRF-TOKEN':$('meta[name="_token"]').attr('content'),},success:function(data){defaultPage=data.page+1
$('.loaded-data').append(data.html)
if(data.hasMorePages==false){$('#load-more-period').remove()}},error:function(xhr,type){console.log('Ajax error!')},})})
$('#load-more-category').on('click',function(e){e.preventDefault()
var category=$(this).data('category')
$.ajax({type:'GET',url:'/ajax/category/more',data:{page:defaultPage,category:category,},dataType:'json',headers:{'X-CSRF-TOKEN':$('meta[name="_token"]').attr('content'),},success:function(data){defaultPage=data.page+1
$('.loaded-data').append(data.html)
if(data.hasMorePages==false){$('#load-more-category').remove()}},error:function(xhr,type){console.log('Ajax error!')},})})
function hide_banner(){$('.banner-info').fadeOut(1000)}
setTimeout(hide_banner,7000)
$('._submit').on('click',function(e){e.preventDefault()
$(this).parents('form').submit()})
$('.owl-carousel-normal').owlCarousel({rtl:true,loop:false,center:false,margin:10,dots:false,nav:true,navText:['<span class="_scroll right i-ar-r"></span>','<span class="_scroll left i-ar-l"></span>'],navElement:'div',responsive:{0:{items:2,slideBy:1},450:{items:3,slideBy:1},600:{items:4,slideBy:2},800:{items:5,slideBy:3},921:{items:4,slideBy:2},1120:{items:5,slideBy:3},},})
$('.owl-carousel-wide').owlCarousel({rtl:true,loop:false,center:false,margin:10,dots:false,nav:true,navText:['<span class="_scroll right i-ar-r"></span>','<span class="_scroll left i-ar-l"></span>'],navElement:'div',responsive:{0:{items:2,slideBy:1},450:{items:3,slideBy:1},600:{items:4,slideBy:2},800:{items:5,slideBy:3},921:{items:4,slideBy:2},1120:{items:5,slideBy:3},},})
$('.search-show').on('click',function(e){e.preventDefault()
$('.switch-color').addClass('hide')
$('.topsrch').toggle()})
$('.color-switcher').on('click',function(e){e.preventDefault()
$('.switch-color').toggleClass('hide')})
$('.show-menu').on('click',function(e){e.preventDefault()
$('#right').toggleClass('show_full')})
$('._darkmode').on('change',function(e){if($(this).prop('checked')){$('body').addClass('dark')}else{$('body').removeClass('dark')}})
$('#share').jsSocials({showLabel:false,showCount:false,shares:['twitter','facebook','email','whatsapp'],})
$('.q.autoComplete').keyup(function(){var q=$(this).parents('form').find('input[name=q]').val()
var _token=$(this).parents('form').find('input[name=_token]').val()
console.log([_token,q],q.length)
if(q.length>2){$.ajax({type:'GET',url:'/search/auto-complete?_token='+_token+'&q='+q,success:function(data){$('.p._clear').removeClass('hide')
$('.slist').removeClass('hide').html(data)},})}else{$('.p._clear').addClass('hide')
$('.slist').addClass('hide').html('')}})
$('.p._clear').on('click',function(e){e.preventDefault()
$('.p._clear').addClass('hide')
$('.slist').addClass('hide').html('')})
$('.click_ads').on('click',function(e){e.preventDefault();var ads_url=$(this).data('ads');console.log(ads_url);})})
function getUrlParameter(sParam){var sPageURL=window.location.search.substring(1),sURLVariables=sPageURL.split('&'),sParameterName,i
for(i=0;i<sURLVariables.length;i++){sParameterName=sURLVariables[i].split('=')
if(sParameterName[0]===sParam){return sParameterName[1]===undefined?true:decodeURIComponent(sParameterName[1])}}}